# YOLO 微调配置文件
train: ./dataset/train/images
val: ./dataset/val/images

nc: 10

# 类别
names: ['Computer keyboard', 'Pen', 'Book', 'Tablet computer', 'Mobile phone', 'Laptop', 'Person', 'Computer mouse', 'Human hand', 'Human head']
